DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(40) NOT NULL UNIQUE,
  password VARCHAR(40) NOT NULL,
  admin TINYINT NOT NULL,
  PRIMARY KEY (id)
) DEFAULT CHARSET=utf8;

CREATE TABLE room (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT,
  size TINYINT NOT NULL NOT NULL,
  sea_viewable TINYINT NOT NULL,
  free_minibar TINYINT NOT NULL,
  description_en VARCHAR(255) NULL,
  description_ru VARCHAR(255) NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES user(id)
) DEFAULT CHARSET=utf8;